version: '3.7'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
  bot:
    build: .
    ports:
      - "15848:15848"
    command: sh -c "python3 main.py"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
